version: 0.2

phases:
  pre_build:
    commands:
      - echo Building Lambda deployment package...
      - cd services/event-simulator

  build:
    commands:
      - echo Build started on `date`
      - |
        # Clean previous build
        rm -rf package lambda-deployment.zip
        
        # Create package directory
        mkdir -p package
        
        # Install dependencies
        pip install -r requirements.txt -t package/
        
        # Copy source files
        cp src/*.py package/
        cp -r src/generators package/
        
        # Create zip
        cd package
        zip -r ../lambda-deployment.zip . -x "*.pyc" -x "__pycache__/*"
        cd ..
        
      - echo Package created successfully
      - ls -lh lambda-deployment.zip

  post_build:
    commands:
      - echo Deploying to Lambda function...
      - |
        FUNCTION_NAME="$PROJECT_NAME-event-generator"
        echo "Updating $FUNCTION_NAME..."
        
        aws lambda update-function-code \
          --function-name $FUNCTION_NAME \
          --zip-file fileb://lambda-deployment.zip \
          --region $AWS_DEFAULT_REGION
        
        echo "✅ $FUNCTION_NAME updated successfully"
      - echo Deployment completed on `date`
