"""
⚠️  AUTO-GENERATED FROM AVRO SCHEMA
This file is generated by scripts/generate-models.sh
DO NOT EDIT MANUALLY - Changes will be overwritten
To modify: Edit the Avro schema in scripts/schemas/avro/ and regenerate
"""

from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime

class Alert(BaseModel):
    """Fraud alert with all metadata and context"""
    alertId: int
    alertType: str
    domain: str
    actorId: str
    severity: str
    fraudScore: int
    transactionCount: int
    totalAmount: float
    firstSeen: datetime
    lastSeen: datetime
    windowSeconds: Optional[int] = None
    baselineAvg: Optional[float] = None
    patternsDetected: Optional[List[str]] = None
    confidence: Optional[int] = None
    modelVersion: Optional[str] = None
    inferenceTimeMs: Optional[int] = None
    playerId: Optional[str] = None
    gameId: Optional[str] = None
    itemType: Optional[str] = None
    itemName: Optional[str] = None
    sessionLengthSec: Optional[int] = None
    accountFrom: Optional[str] = None
    accountTo: Optional[str] = None
    transferType: Optional[str] = None
    countryFrom: Optional[str] = None
    countryTo: Optional[str] = None
    purpose: Optional[str] = None
    userId: Optional[str] = None
    cartItems: Optional[str] = None
    shippingAddress: Optional[str] = None
    billingAddress: Optional[str] = None
    deviceFingerprint: Optional[str] = None
    sessionDurationSec: Optional[int] = None
    paymentMethod: Optional[str] = None
    deviceId: Optional[str] = None
    ipAddress: Optional[str] = None
